"""initial migration

Revision ID: 1070267cb6ba
Revises: None
Create Date: 2014-05-13 19:57:01.675583

"""

# revision identifiers, used by Alembic.
revision = '1070267cb6ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
